name: CI  
on: [pull_request, workflow_run]
jobs:
  build:
      runs-on: ubuntu-latest
          steps:
                - uses: actions/checkout@v3
                      - name: Step 1
                              run: echo hello
                                    - name: Step 2
                                            run: echo world
                                            
